[2023-11-12T11:03:23.807+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_dag_postgres.create_vaccinations_query_operator manual__2023-11-12T11:03:04.014305+00:00 [queued]>
[2023-11-12T11:03:23.909+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_dag_postgres.create_vaccinations_query_operator manual__2023-11-12T11:03:04.014305+00:00 [queued]>
[2023-11-12T11:03:23.911+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-11-12T11:03:24.186+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): create_vaccinations_query_operator> on 2023-11-12 11:03:04.014305+00:00
[2023-11-12T11:03:24.245+0000] {standard_task_runner.py:57} INFO - Started process 375 to run task
[2023-11-12T11:03:24.255+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_dag_postgres', 'create_vaccinations_query_operator', 'manual__2023-11-12T11:03:04.014305+00:00', '--job-id', '773', '--raw', '--subdir', 'DAGS_FOLDER/Dag_postgres.py', '--cfg-path', '/tmp/tmp3nsg2sxr']
[2023-11-12T11:03:24.320+0000] {standard_task_runner.py:85} INFO - Job 773: Subtask create_vaccinations_query_operator
[2023-11-12T11:03:24.879+0000] {task_command.py:415} INFO - Running <TaskInstance: covid_data_dag_postgres.create_vaccinations_query_operator manual__2023-11-12T11:03:04.014305+00:00 [running]> on host 172.21.0.6
[2023-11-12T11:03:27.631+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-11-12T11:03:27.885+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_dag_postgres' AIRFLOW_CTX_TASK_ID='create_vaccinations_query_operator' AIRFLOW_CTX_EXECUTION_DATE='2023-11-12T11:03:04.014305+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-12T11:03:04.014305+00:00'
[2023-11-12T11:03:29.289+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Dag_postgres.py", line 152, in _create_vaccinations_query
    df.fillna(None, inplace=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 5493, in fillna
    return super().fillna(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6859, in fillna
    value, method = validate_fillna_kwargs(value, method)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/util/_validators.py", line 288, in validate_fillna_kwargs
    raise ValueError("Must specify a fill 'value' or 'method'.")
ValueError: Must specify a fill 'value' or 'method'.
[2023-11-12T11:03:29.518+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=covid_data_dag_postgres, task_id=create_vaccinations_query_operator, execution_date=20231112T110304, start_date=20231112T110323, end_date=20231112T110329
[2023-11-12T11:03:29.568+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 773 for task create_vaccinations_query_operator (Must specify a fill 'value' or 'method'.; 375)
[2023-11-12T11:03:29.640+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-12T11:03:30.375+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
