[2023-11-08T12:14:43.630+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_dag.create_vaccinations_query_operator manual__2023-11-08T12:14:09.228120+00:00 [queued]>
[2023-11-08T12:14:43.643+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_dag.create_vaccinations_query_operator manual__2023-11-08T12:14:09.228120+00:00 [queued]>
[2023-11-08T12:14:43.644+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2023-11-08T12:14:43.663+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): create_vaccinations_query_operator> on 2023-11-08 12:14:09.228120+00:00
[2023-11-08T12:14:43.670+0000] {standard_task_runner.py:57} INFO - Started process 2235 to run task
[2023-11-08T12:14:43.675+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_dag', 'create_vaccinations_query_operator', 'manual__2023-11-08T12:14:09.228120+00:00', '--job-id', '320', '--raw', '--subdir', 'DAGS_FOLDER/Dag_postgres.py', '--cfg-path', '/tmp/tmp3bi2ayk2']
[2023-11-08T12:14:43.681+0000] {standard_task_runner.py:85} INFO - Job 320: Subtask create_vaccinations_query_operator
[2023-11-08T12:14:43.775+0000] {task_command.py:415} INFO - Running <TaskInstance: covid_data_dag.create_vaccinations_query_operator manual__2023-11-08T12:14:09.228120+00:00 [running]> on host 172.21.0.9
[2023-11-08T12:14:43.868+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-11-08T12:14:43.934+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_dag' AIRFLOW_CTX_TASK_ID='create_vaccinations_query_operator' AIRFLOW_CTX_EXECUTION_DATE='2023-11-08T12:14:09.228120+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-08T12:14:09.228120+00:00'
[2023-11-08T12:14:44.580+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Dag_postgres.py", line 140, in _create_vaccinations_query
    counter+=1
UnboundLocalError: local variable 'counter' referenced before assignment
[2023-11-08T12:14:44.604+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=covid_data_dag, task_id=create_vaccinations_query_operator, execution_date=20231108T121409, start_date=20231108T121443, end_date=20231108T121444
[2023-11-08T12:14:44.640+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 320 for task create_vaccinations_query_operator (local variable 'counter' referenced before assignment; 2235)
[2023-11-08T12:14:44.696+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-08T12:14:44.739+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
