[2023-11-15T19:54:53.805+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_dag_postgres_plis.staging.wrangle_cases_deaths manual__2023-11-15T19:54:19.262740+00:00 [queued]>
[2023-11-15T19:54:53.860+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_dag_postgres_plis.staging.wrangle_cases_deaths manual__2023-11-15T19:54:19.262740+00:00 [queued]>
[2023-11-15T19:54:53.862+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-11-15T19:54:53.952+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): staging.wrangle_cases_deaths> on 2023-11-15 19:54:19.262740+00:00
[2023-11-15T19:54:53.973+0000] {standard_task_runner.py:57} INFO - Started process 8133 to run task
[2023-11-15T19:54:54.030+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_dag_postgres_plis', 'staging.wrangle_cases_deaths', 'manual__2023-11-15T19:54:19.262740+00:00', '--job-id', '1076', '--raw', '--subdir', 'DAGS_FOLDER/Dag_postgres.py', '--cfg-path', '/tmp/tmp5eoemirr']
[2023-11-15T19:54:54.040+0000] {standard_task_runner.py:85} INFO - Job 1076: Subtask staging.wrangle_cases_deaths
[2023-11-15T19:54:54.243+0000] {task_command.py:415} INFO - Running <TaskInstance: covid_data_dag_postgres_plis.staging.wrangle_cases_deaths manual__2023-11-15T19:54:19.262740+00:00 [running]> on host 172.21.0.9
[2023-11-15T19:54:54.907+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_dag_postgres_plis' AIRFLOW_CTX_TASK_ID='staging.wrangle_cases_deaths' AIRFLOW_CTX_EXECUTION_DATE='2023-11-15T19:54:19.262740+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-15T19:54:19.262740+00:00'
[2023-11-15T19:54:56.266+0000] {logging_mixin.py:151} INFO - Formatting date…
[2023-11-15T19:54:56.550+0000] {logging_mixin.py:151} INFO - Discarding rows…
[2023-11-15T19:55:05.438+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Dag_postgres.py", line 168, in _wrangle_cases_deaths
    df = convert_iso_code(df)
NameError: name 'convert_iso_code' is not defined
[2023-11-15T19:55:05.458+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=covid_data_dag_postgres_plis, task_id=staging.wrangle_cases_deaths, execution_date=20231115T195419, start_date=20231115T195453, end_date=20231115T195505
[2023-11-15T19:55:05.485+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1076 for task staging.wrangle_cases_deaths (name 'convert_iso_code' is not defined; 8133)
[2023-11-15T19:55:05.549+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-15T19:55:05.631+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
