[2023-11-19T11:30:28.441+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_dag_postgres_plis.staging.upload_vaccinations manual__2023-11-19T11:28:36.055752+00:00 [queued]>
[2023-11-19T11:30:28.593+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_dag_postgres_plis.staging.upload_vaccinations manual__2023-11-19T11:28:36.055752+00:00 [queued]>
[2023-11-19T11:30:28.596+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2023-11-19T11:30:28.707+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): staging.upload_vaccinations> on 2023-11-19 11:28:36.055752+00:00
[2023-11-19T11:30:28.717+0000] {standard_task_runner.py:57} INFO - Started process 2319 to run task
[2023-11-19T11:30:28.759+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_dag_postgres_plis', 'staging.upload_vaccinations', 'manual__2023-11-19T11:28:36.055752+00:00', '--job-id', '1228', '--raw', '--subdir', 'DAGS_FOLDER/Dag_postgres.py', '--cfg-path', '/tmp/tmpzdcd90ib']
[2023-11-19T11:30:28.789+0000] {standard_task_runner.py:85} INFO - Job 1228: Subtask staging.upload_vaccinations
[2023-11-19T11:30:31.900+0000] {task_command.py:415} INFO - Running <TaskInstance: covid_data_dag_postgres_plis.staging.upload_vaccinations manual__2023-11-19T11:28:36.055752+00:00 [running]> on host 172.21.0.3
[2023-11-19T11:30:32.411+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_dag_postgres_plis' AIRFLOW_CTX_TASK_ID='staging.upload_vaccinations' AIRFLOW_CTX_EXECUTION_DATE='2023-11-19T11:28:36.055752+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-19T11:28:36.055752+00:00'
[2023-11-19T11:30:39.064+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Dag_postgres.py", line 221, in _upload_vaccinations
    df.to_sql('vaccinations', con='postgres_default', if_exists='replace', index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 768, in to_sql
    with pandasSQL_builder(con, schema=schema, need_transaction=True) as pandas_sql:
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 832, in pandasSQL_builder
    return SQLDatabase(con, schema, need_transaction)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1536, in __init__
    con = create_engine(con)
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 514, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 738, in make_url
    return _parse_url(name_or_url)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 799, in _parse_url
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not parse SQLAlchemy URL from string 'postgres_default'
[2023-11-19T11:30:39.766+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=covid_data_dag_postgres_plis, task_id=staging.upload_vaccinations, execution_date=20231119T112836, start_date=20231119T113028, end_date=20231119T113039
[2023-11-19T11:30:40.038+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1228 for task staging.upload_vaccinations (Could not parse SQLAlchemy URL from string 'postgres_default'; 2319)
[2023-11-19T11:30:40.278+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-19T11:30:40.350+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
