[2023-11-08T11:02:26.442+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_dag.create_vaccinations_table manual__2023-11-08T11:02:04.745651+00:00 [queued]>
[2023-11-08T11:02:26.493+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_dag.create_vaccinations_table manual__2023-11-08T11:02:04.745651+00:00 [queued]>
[2023-11-08T11:02:26.494+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-11-08T11:02:26.528+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): create_vaccinations_table> on 2023-11-08 11:02:04.745651+00:00
[2023-11-08T11:02:26.543+0000] {standard_task_runner.py:57} INFO - Started process 5220 to run task
[2023-11-08T11:02:26.566+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_dag', 'create_vaccinations_table', 'manual__2023-11-08T11:02:04.745651+00:00', '--job-id', '230', '--raw', '--subdir', 'DAGS_FOLDER/Dag_postgres.py', '--cfg-path', '/tmp/tmpnnndcme6']
[2023-11-08T11:02:26.573+0000] {standard_task_runner.py:85} INFO - Job 230: Subtask create_vaccinations_table
[2023-11-08T11:02:26.744+0000] {task_command.py:415} INFO - Running <TaskInstance: covid_data_dag.create_vaccinations_table manual__2023-11-08T11:02:04.745651+00:00 [running]> on host 172.21.0.5
[2023-11-08T11:02:27.066+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_dag' AIRFLOW_CTX_TASK_ID='create_vaccinations_table' AIRFLOW_CTX_EXECUTION_DATE='2023-11-08T11:02:04.745651+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-08T11:02:04.745651+00:00'
[2023-11-08T11:02:27.068+0000] {sql.py:274} INFO - Executing: CREATE TABLE IF NOT EXISTS vaccinations (id SERIAL PRIMARY KEY,iso_code VARCHAR(10),date DATE,total_vaccinations INTEGER,people_vaccinated INTEGER,people_fully_vaccinated INTEGER,daily_vaccinations_raw INTEGER,daily_vaccinations INTEGER,total_vaccinations_per_hundred FLOAT,people_vaccinated_per_hundred FLOAT,people_fully_vaccinated_per_hundred FLOAT,daily_vaccinations_per_million INTEGER,vaccines VARCHAR(100),source_name VARCHAR(100),source_website VARCHAR(100));
[2023-11-08T11:02:27.087+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2023-11-08T11:02:27.112+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2023-11-08T11:02:27.119+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

[2023-11-08T11:02:27.156+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=covid_data_dag, task_id=create_vaccinations_table, execution_date=20231108T110204, start_date=20231108T110226, end_date=20231108T110227
[2023-11-08T11:02:27.229+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 230 for task create_vaccinations_table (connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
; 5220)
[2023-11-08T11:02:27.349+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-08T11:02:27.459+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
