[2023-11-08T12:51:14.875+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_dag.create_vaccinations_query_operator manual__2023-11-08T12:47:59.375380+00:00 [queued]>
[2023-11-08T12:51:15.049+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_dag.create_vaccinations_query_operator manual__2023-11-08T12:47:59.375380+00:00 [queued]>
[2023-11-08T12:51:15.055+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2023-11-08T12:51:15.287+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): create_vaccinations_query_operator> on 2023-11-08 12:47:59.375380+00:00
[2023-11-08T12:51:15.397+0000] {standard_task_runner.py:57} INFO - Started process 3697 to run task
[2023-11-08T12:51:15.550+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_dag', 'create_vaccinations_query_operator', 'manual__2023-11-08T12:47:59.375380+00:00', '--job-id', '390', '--raw', '--subdir', 'DAGS_FOLDER/Dag_postgres.py', '--cfg-path', '/tmp/tmpylorru84']
[2023-11-08T12:51:15.606+0000] {standard_task_runner.py:85} INFO - Job 390: Subtask create_vaccinations_query_operator
[2023-11-08T12:51:27.127+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-11-08T12:51:27.280+0000] {process_utils.py:131} INFO - Sending 15 to group 3697. PIDs of all processes in the group: [3697]
[2023-11-08T12:51:27.286+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 3697
[2023-11-08T12:51:27.698+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3697, status='terminated', exitcode=0, started='12:51:15') (3697) terminated with exit code 0
