[2023-11-15T19:31:11.168+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_dag_postgres_plis.staging.wrangle_cases_deaths manual__2023-11-15T19:29:58.102430+00:00 [queued]>
[2023-11-15T19:31:11.209+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_dag_postgres_plis.staging.wrangle_cases_deaths manual__2023-11-15T19:29:58.102430+00:00 [queued]>
[2023-11-15T19:31:11.210+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2023-11-15T19:31:11.249+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): staging.wrangle_cases_deaths> on 2023-11-15 19:29:58.102430+00:00
[2023-11-15T19:31:11.261+0000] {standard_task_runner.py:57} INFO - Started process 7268 to run task
[2023-11-15T19:31:11.281+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_dag_postgres_plis', 'staging.wrangle_cases_deaths', 'manual__2023-11-15T19:29:58.102430+00:00', '--job-id', '1041', '--raw', '--subdir', 'DAGS_FOLDER/Dag_postgres.py', '--cfg-path', '/tmp/tmpa04iodip']
[2023-11-15T19:31:11.293+0000] {standard_task_runner.py:85} INFO - Job 1041: Subtask staging.wrangle_cases_deaths
[2023-11-15T19:31:13.176+0000] {task_command.py:415} INFO - Running <TaskInstance: covid_data_dag_postgres_plis.staging.wrangle_cases_deaths manual__2023-11-15T19:29:58.102430+00:00 [running]> on host 172.21.0.9
[2023-11-15T19:31:13.300+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_dag_postgres_plis' AIRFLOW_CTX_TASK_ID='staging.wrangle_cases_deaths' AIRFLOW_CTX_EXECUTION_DATE='2023-11-15T19:29:58.102430+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-15T19:29:58.102430+00:00'
[2023-11-15T19:31:13.876+0000] {logging_mixin.py:151} INFO - Formatting date…
[2023-11-15T19:31:13.967+0000] {logging_mixin.py:151} INFO - Discarding rows…
[2023-11-15T19:31:14.737+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Dag_postgres.py", line 168, in _wrangle_cases_deaths
    df = convert_iso_code(df)
NameError: name 'convert_iso_code' is not defined
[2023-11-15T19:31:14.755+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=covid_data_dag_postgres_plis, task_id=staging.wrangle_cases_deaths, execution_date=20231115T192958, start_date=20231115T193111, end_date=20231115T193114
[2023-11-15T19:31:14.776+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1041 for task staging.wrangle_cases_deaths (name 'convert_iso_code' is not defined; 7268)
[2023-11-15T19:31:14.810+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-15T19:31:15.102+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
