[2023-11-07T14:26:02.834+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_dag.create_government_measures_table manual__2023-11-07T14:25:28.286289+00:00 [queued]>
[2023-11-07T14:26:02.906+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_dag.create_government_measures_table manual__2023-11-07T14:25:28.286289+00:00 [queued]>
[2023-11-07T14:26:02.907+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-11-07T14:26:03.031+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): create_government_measures_table> on 2023-11-07 14:25:28.286289+00:00
[2023-11-07T14:26:03.056+0000] {standard_task_runner.py:57} INFO - Started process 217 to run task
[2023-11-07T14:26:03.085+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_dag', 'create_government_measures_table', 'manual__2023-11-07T14:25:28.286289+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/Dags.py', '--cfg-path', '/tmp/tmpdlb0s6en']
[2023-11-07T14:26:03.146+0000] {standard_task_runner.py:85} INFO - Job 84: Subtask create_government_measures_table
[2023-11-07T14:26:03.430+0000] {task_command.py:415} INFO - Running <TaskInstance: covid_data_dag.create_government_measures_table manual__2023-11-07T14:25:28.286289+00:00 [running]> on host 172.21.0.8
[2023-11-07T14:26:03.595+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_dag' AIRFLOW_CTX_TASK_ID='create_government_measures_table' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T14:25:28.286289+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-07T14:25:28.286289+00:00'
[2023-11-07T14:26:03.596+0000] {sql.py:274} INFO - Executing: CREATE TABLE IF NOT EXISTS government_measures (id SERIAL PRIMARY KEY,country_name VARCHAR(100),region_name VARCHAR(100),date DATE,c1_school_closing INTEGER,c1_flag INTEGER,c2_workplace_closing INTEGER,c2_flag INTEGER,c3_cancel_public_events INTEGER,c3_flag INTEGER,c4_restrictions_on_gatherings INTEGER,c4_flag INTEGER,c5_close_public_transport INTEGER,c5_flag INTEGER,c6_stay_at_home_requirements INTEGER,c6_flag INTEGER,c7_restrictions_on_internal_movement INTEGER,c7_flag INTEGER,c8_international_travel_controls INTEGER,h1_public_information_campaigns INTEGER,h1_flag INTEGER,h2_testing_policy INTEGER,h3_contact_tracing INTEGER,h4_emergency_investment_in_healthcare INTEGER,h5_investment_in_vaccines INTEGER,m1_wildcard INTEGER,stringency_index FLOAT,stringency_index_for_display FLOAT,stringency_legacy_index FLOAT,stringency_legacy_index_for_display FLOAT,government_response_index FLOAT,government_response_index_for_display FLOAT,containment_health_index FLOAT,containment_health_index_for_display FLOAT,economic_support_index FLOAT,economic_support_index_for_display FLOAT);
[2023-11-07T14:26:03.629+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 275, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 186, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 148, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2023-11-07T14:26:03.636+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=covid_data_dag, task_id=create_government_measures_table, execution_date=20231107T142528, start_date=20231107T142602, end_date=20231107T142603
[2023-11-07T14:26:03.657+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 84 for task create_government_measures_table (The conn_id `postgres_default` isn't defined; 217)
[2023-11-07T14:26:03.676+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-07T14:26:03.772+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
