[2023-11-14T18:11:54.461+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_dag_postgres.download_country_mapping manual__2023-11-14T18:11:19.655016+00:00 [queued]>
[2023-11-14T18:11:54.609+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_dag_postgres.download_country_mapping manual__2023-11-14T18:11:19.655016+00:00 [queued]>
[2023-11-14T18:11:54.610+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-11-14T18:11:54.662+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): download_country_mapping> on 2023-11-14 18:11:19.655016+00:00
[2023-11-14T18:11:54.695+0000] {standard_task_runner.py:57} INFO - Started process 17908 to run task
[2023-11-14T18:11:55.590+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_dag_postgres', 'download_country_mapping', 'manual__2023-11-14T18:11:19.655016+00:00', '--job-id', '933', '--raw', '--subdir', 'DAGS_FOLDER/Dag_postgres.py', '--cfg-path', '/tmp/tmpufggr0jo']
[2023-11-14T18:11:55.868+0000] {standard_task_runner.py:85} INFO - Job 933: Subtask download_country_mapping
[2023-11-14T18:16:47.764+0000] {task_command.py:415} INFO - Running <TaskInstance: covid_data_dag_postgres.download_country_mapping manual__2023-11-14T18:11:19.655016+00:00 [running]> on host 172.21.0.4
[2023-11-14T18:16:48.676+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_dag_postgres' AIRFLOW_CTX_TASK_ID='download_country_mapping' AIRFLOW_CTX_EXECUTION_DATE='2023-11-14T18:11:19.655016+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-14T18:11:19.655016+00:00'
[2023-11-14T18:16:48.717+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-14T18:16:48.732+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'kaggle datasets download -d andradaolteanu/country-mapping-iso-continent-region']
[2023-11-14T18:16:50.742+0000] {subprocess.py:86} INFO - Output:
[2023-11-14T18:16:50.965+0000] {subprocess.py:93} INFO - /bin/bash: line 1: kaggle: command not found
[2023-11-14T18:16:50.987+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-11-14T18:16:51.242+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-11-14T18:16:51.522+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=covid_data_dag_postgres, task_id=download_country_mapping, execution_date=20231114T181119, start_date=20231114T181154, end_date=20231114T181651
[2023-11-14T18:16:51.850+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 933 for task download_country_mapping (Bash command failed. The command returned a non-zero exit code 127.; 17908)
[2023-11-14T18:16:52.221+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-14T18:16:52.912+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
