[2023-11-07T14:26:06.326+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_dag.create_vaccinations_table manual__2023-11-07T14:25:28.286289+00:00 [queued]>
[2023-11-07T14:26:06.347+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_dag.create_vaccinations_table manual__2023-11-07T14:25:28.286289+00:00 [queued]>
[2023-11-07T14:26:06.348+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-11-07T14:26:06.387+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): create_vaccinations_table> on 2023-11-07 14:25:28.286289+00:00
[2023-11-07T14:26:06.398+0000] {standard_task_runner.py:57} INFO - Started process 222 to run task
[2023-11-07T14:26:06.413+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_dag', 'create_vaccinations_table', 'manual__2023-11-07T14:25:28.286289+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/Dags.py', '--cfg-path', '/tmp/tmpglccpv0s']
[2023-11-07T14:26:06.421+0000] {standard_task_runner.py:85} INFO - Job 86: Subtask create_vaccinations_table
[2023-11-07T14:26:06.531+0000] {task_command.py:415} INFO - Running <TaskInstance: covid_data_dag.create_vaccinations_table manual__2023-11-07T14:25:28.286289+00:00 [running]> on host 172.21.0.8
[2023-11-07T14:26:06.650+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_dag' AIRFLOW_CTX_TASK_ID='create_vaccinations_table' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T14:25:28.286289+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-07T14:25:28.286289+00:00'
[2023-11-07T14:26:06.651+0000] {sql.py:274} INFO - Executing: CREATE TABLE IF NOT EXISTS vaccinations (id SERIAL PRIMARY KEY,iso_code VARCHAR(10),date DATE,total_vaccinations INTEGER,people_vaccinated INTEGER,people_fully_vaccinated INTEGER,daily_vaccinations_raw INTEGER,daily_vaccinations INTEGER,total_vaccinations_per_hundred FLOAT,people_vaccinated_per_hundred FLOAT,people_fully_vaccinated_per_hundred FLOAT,daily_vaccinations_per_million INTEGER,vaccines VARCHAR(100),source_name VARCHAR(100),source_website VARCHAR(100));
[2023-11-07T14:26:06.677+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 275, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 186, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 148, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2023-11-07T14:26:06.682+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=covid_data_dag, task_id=create_vaccinations_table, execution_date=20231107T142528, start_date=20231107T142606, end_date=20231107T142606
[2023-11-07T14:26:06.698+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 86 for task create_vaccinations_table (The conn_id `postgres_default` isn't defined; 222)
[2023-11-07T14:26:06.742+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-07T14:26:06.780+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
