[2023-11-24T19:11:08.631+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_dag_postgres_plis.staging.wrangle_cases_deaths manual__2023-11-24T18:57:23.260150+00:00 [queued]>
[2023-11-24T19:11:08.696+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_dag_postgres_plis.staging.wrangle_cases_deaths manual__2023-11-24T18:57:23.260150+00:00 [queued]>
[2023-11-24T19:11:08.760+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-11-24T19:11:08.855+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): staging.wrangle_cases_deaths> on 2023-11-24 18:57:23.260150+00:00
[2023-11-24T19:11:08.888+0000] {standard_task_runner.py:57} INFO - Started process 4440 to run task
[2023-11-24T19:11:08.928+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_dag_postgres_plis', 'staging.wrangle_cases_deaths', 'manual__2023-11-24T18:57:23.260150+00:00', '--job-id', '1502', '--raw', '--subdir', 'DAGS_FOLDER/Dag_postgres.py', '--cfg-path', '/tmp/tmp4bm286g1']
[2023-11-24T19:11:08.959+0000] {standard_task_runner.py:85} INFO - Job 1502: Subtask staging.wrangle_cases_deaths
[2023-11-24T19:11:09.087+0000] {task_command.py:415} INFO - Running <TaskInstance: covid_data_dag_postgres_plis.staging.wrangle_cases_deaths manual__2023-11-24T18:57:23.260150+00:00 [running]> on host 172.21.0.6
[2023-11-24T19:11:09.460+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_dag_postgres_plis' AIRFLOW_CTX_TASK_ID='staging.wrangle_cases_deaths' AIRFLOW_CTX_EXECUTION_DATE='2023-11-24T18:57:23.260150+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-24T18:57:23.260150+00:00'
[2023-11-24T19:11:10.638+0000] {logging_mixin.py:151} INFO - Formatting date…
[2023-11-24T19:11:11.006+0000] {logging_mixin.py:151} INFO - Discarding rows…
[2023-11-24T19:11:12.138+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Dag_postgres.py", line 258, in _wrangle_cases_deaths
    df = _inject_population(df)
  File "/opt/airflow/dags/Dag_postgres.py", line 230, in _inject_population
    df_merged = pd.merge(df, df_population, how='left', on=['Country', 'Year'])
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 148, in merge
    op = _MergeOperation(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 737, in __init__
    ) = self._get_merge_keys()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 1203, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 1778, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'Year'
[2023-11-24T19:11:12.191+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=covid_data_dag_postgres_plis, task_id=staging.wrangle_cases_deaths, execution_date=20231124T185723, start_date=20231124T191108, end_date=20231124T191112
[2023-11-24T19:11:16.764+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1502 for task staging.wrangle_cases_deaths ('Year'; 4440)
[2023-11-24T19:11:16.829+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-24T19:11:16.947+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
