[2023-11-07T15:43:37.393+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_dag.create_cases_deaths_table manual__2023-11-07T15:34:02.567747+00:00 [queued]>
[2023-11-07T15:43:37.404+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_dag.create_cases_deaths_table manual__2023-11-07T15:34:02.567747+00:00 [queued]>
[2023-11-07T15:43:37.405+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2023-11-07T15:43:37.429+0000] {taskinstance.py:1380} INFO - Executing <Task(PostgresOperator): create_cases_deaths_table> on 2023-11-07 15:34:02.567747+00:00
[2023-11-07T15:43:37.435+0000] {standard_task_runner.py:57} INFO - Started process 3255 to run task
[2023-11-07T15:43:37.440+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_dag', 'create_cases_deaths_table', 'manual__2023-11-07T15:34:02.567747+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/Dags.py', '--cfg-path', '/tmp/tmpje6_rm5x']
[2023-11-07T15:43:37.443+0000] {standard_task_runner.py:85} INFO - Job 106: Subtask create_cases_deaths_table
[2023-11-07T15:43:37.495+0000] {task_command.py:415} INFO - Running <TaskInstance: covid_data_dag.create_cases_deaths_table manual__2023-11-07T15:34:02.567747+00:00 [running]> on host 172.21.0.8
[2023-11-07T15:43:37.583+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_dag' AIRFLOW_CTX_TASK_ID='create_cases_deaths_table' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T15:34:02.567747+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-07T15:34:02.567747+00:00'
[2023-11-07T15:43:37.584+0000] {sql.py:274} INFO - Executing: CREATE TABLE IF NOT EXISTS cases_deaths (id SERIAL PRIMARY KEY,date_reported DATE,country_code VARCHAR(10),country VARCHAR(100),who_region VARCHAR(100),new_cases INTEGER,cumulative_cases INTEGER,new_deaths INTEGER,cumulative_deaths INTEGER);
[2023-11-07T15:43:37.593+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2023-11-07T15:43:37.607+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2023-11-07T15:43:37.613+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "172.21.0.3", port 5432 failed: FATAL:  database "db" does not exist

[2023-11-07T15:43:37.623+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=covid_data_dag, task_id=create_cases_deaths_table, execution_date=20231107T153402, start_date=20231107T154337, end_date=20231107T154337
[2023-11-07T15:43:37.637+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 106 for task create_cases_deaths_table (connection to server at "172.21.0.3", port 5432 failed: FATAL:  database "db" does not exist
; 3255)
[2023-11-07T15:43:37.665+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-07T15:43:37.690+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
