[2023-11-26T16:10:39.747+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_dag_postgres_plis.staging.wrangle_cases_deaths manual__2023-11-26T16:05:07.277984+00:00 [queued]>
[2023-11-26T16:10:39.770+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_dag_postgres_plis.staging.wrangle_cases_deaths manual__2023-11-26T16:05:07.277984+00:00 [queued]>
[2023-11-26T16:10:39.771+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2023-11-26T16:10:39.803+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): staging.wrangle_cases_deaths> on 2023-11-26 16:05:07.277984+00:00
[2023-11-26T16:10:39.811+0000] {standard_task_runner.py:57} INFO - Started process 369 to run task
[2023-11-26T16:10:39.817+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_dag_postgres_plis', 'staging.wrangle_cases_deaths', 'manual__2023-11-26T16:05:07.277984+00:00', '--job-id', '1530', '--raw', '--subdir', 'DAGS_FOLDER/Dag_postgres.py', '--cfg-path', '/tmp/tmp5r3aacxw']
[2023-11-26T16:10:39.823+0000] {standard_task_runner.py:85} INFO - Job 1530: Subtask staging.wrangle_cases_deaths
[2023-11-26T16:10:40.198+0000] {task_command.py:415} INFO - Running <TaskInstance: covid_data_dag_postgres_plis.staging.wrangle_cases_deaths manual__2023-11-26T16:05:07.277984+00:00 [running]> on host 172.21.0.5
[2023-11-26T16:10:40.439+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_dag_postgres_plis' AIRFLOW_CTX_TASK_ID='staging.wrangle_cases_deaths' AIRFLOW_CTX_EXECUTION_DATE='2023-11-26T16:05:07.277984+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-26T16:05:07.277984+00:00'
[2023-11-26T16:10:46.715+0000] {logging_mixin.py:151} INFO - Formatting date…
[2023-11-26T16:10:46.880+0000] {logging_mixin.py:151} INFO - Discarding rows…
[2023-11-26T16:10:48.192+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Dag_postgres.py", line 259, in _wrangle_cases_deaths
    df = _inject_population(df, date_col="Date_reported")
  File "/opt/airflow/dags/Dag_postgres.py", line 228, in _inject_population
    df['Year'] = pd.DatetimeIndex(date_col).year
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/datetimes.py", line 321, in __new__
    cls._raise_scalar_data_error(data)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5066, in _raise_scalar_data_error
    raise TypeError(
TypeError: DatetimeIndex(...) must be called with a collection of some kind, 'Date_reported' was passed
[2023-11-26T16:10:48.237+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=covid_data_dag_postgres_plis, task_id=staging.wrangle_cases_deaths, execution_date=20231126T160507, start_date=20231126T161039, end_date=20231126T161048
[2023-11-26T16:10:48.325+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1530 for task staging.wrangle_cases_deaths (DatetimeIndex(...) must be called with a collection of some kind, 'Date_reported' was passed; 369)
[2023-11-26T16:10:48.396+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T16:10:48.446+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
