[2023-11-15T19:25:51.095+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: covid_data_dag_postgres_plis.ingestion.download_government_measures manual__2023-11-15T19:25:42.288391+00:00 [queued]>
[2023-11-15T19:25:51.121+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: covid_data_dag_postgres_plis.ingestion.download_government_measures manual__2023-11-15T19:25:42.288391+00:00 [queued]>
[2023-11-15T19:25:51.122+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-11-15T19:25:51.163+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): ingestion.download_government_measures> on 2023-11-15 19:25:42.288391+00:00
[2023-11-15T19:25:51.207+0000] {standard_task_runner.py:57} INFO - Started process 7034 to run task
[2023-11-15T19:25:51.220+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'covid_data_dag_postgres_plis', 'ingestion.download_government_measures', 'manual__2023-11-15T19:25:42.288391+00:00', '--job-id', '1018', '--raw', '--subdir', 'DAGS_FOLDER/Dag_postgres.py', '--cfg-path', '/tmp/tmpn6ltb1y7']
[2023-11-15T19:25:51.233+0000] {standard_task_runner.py:85} INFO - Job 1018: Subtask ingestion.download_government_measures
[2023-11-15T19:25:58.517+0000] {task_command.py:415} INFO - Running <TaskInstance: covid_data_dag_postgres_plis.ingestion.download_government_measures manual__2023-11-15T19:25:42.288391+00:00 [running]> on host 172.21.0.9
[2023-11-15T19:25:58.984+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='covid_data_dag_postgres_plis' AIRFLOW_CTX_TASK_ID='ingestion.download_government_measures' AIRFLOW_CTX_EXECUTION_DATE='2023-11-15T19:25:42.288391+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-15T19:25:42.288391+00:00'
[2023-11-15T19:26:04.946+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Dag_postgres.py", line 77, in _download_government_measures
    with open('/opt/airflow/dags/postgres/government_measures.csv', 'wb') as f:
OSError: [Errno 22] Invalid argument: '/opt/airflow/dags/postgres/government_measures.csv'
[2023-11-15T19:26:05.566+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=covid_data_dag_postgres_plis, task_id=ingestion.download_government_measures, execution_date=20231115T192542, start_date=20231115T192551, end_date=20231115T192605
[2023-11-15T19:26:14.286+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1018 for task ingestion.download_government_measures ([Errno 22] Invalid argument: '/opt/airflow/dags/postgres/government_measures.csv'; 7034)
[2023-11-15T19:26:14.516+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-15T19:26:14.805+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
